### ISSUE TITLE
File access issue

### ISSUE THREAD

**Issue by Mirith** [brianspiering/awesome-dl4nlp#2]
The link to paper 4 under the Papers section does not work, and shows this page when I click it.  
<img width="562" alt="file access" src="https://user-images.githubusercontent.com/23423307/32821378-f1dccde2-c987-11e7-8432-f8d73b9d7b87.PNG">

The link to check outages doesn't mention anything that would affect this either, I think.

**Comment by brianspiering** [comment]
Thanks for bringing that to my attention. I'll look into it and fix it.

**Comment by brianspiering** [comment]
I fixed it. The link now points to Arxiv which should be more stable. Here is the link- https://arxiv.org/abs/1411.2738
